services:
  - type: web
    name: comprahorro-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: static_site
    name: comprahorro-frontend
    buildCommand: cd comprahorro-panama && npm install && npm run build
    publishDir: comprahorro-panama/dist

databases:
  - name: comprahorro-db
    plan: free
