services:
  # 1. El Cerebro (Backend)
  - type: web
    name: comprahorro-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install && ./node_modules/.bin/nest build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # 2. La Cara (Frontend)
  - type: web
    name: comprahorro-frontend
    runtime: static  # <--- Esto le dice a Render que es un sitio estático
    buildCommand: cd comprahorro-panama && npm install && npm run build
    staticPublishPath: comprahorro-panama/dist

databases:
  # 3. Base de Datos
  - name: comprahorro-db
    plan: free
